apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rs47gq9ov-go 
  janus-idp.io/tekton: rs47gq9ov-go
  backstage.io/kubernetes-id: rs47gq9ov-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rs47gq9ov-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  