apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rs47gq9ov-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rs47gq9ov-go 
  name: rs47gq9ov-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rs47gq9ov-go 
